name: Code Blocks

on:
  pull_request: ~

jobs:
  symfony-code-block-checker:
    name: Verify
    runs-on: Ubuntu-20.04
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set-up PHP
        uses: shivammathur/setup-php@v2
        with:
            php-version: 8.0
            coverage: none

      - name: Fetch branch from where the PR started
        run: git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*

      - name: Find modified files
        id: find-files
        run: echo "::set-output name=files::$(git diff --name-only origin/${{ github.base_ref }} HEAD | grep ".rst" | tr '\n' ' ')"

      - name: Get composer cache directory
        id: composercache
        working-directory: _build
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
            path: ${{ steps.composercache.outputs.dir }}
            key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
            restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        if: ${{ steps.find-files.outputs.files }}
        run: |
          git clone --depth 15 https://github.com/symfony-docs-tools/code-block-checker.git ../_checker
          cd ../_checker
          composer install

      - name: Generate baseline
        if: ${{ steps.find-files.outputs.files }}
        run: |
          CURRENT=$(git rev-parse HEAD)
          git checkout -m ${{ github.base_ref }}
          ../_checker/code-block-checker.php verify:docs `pwd` ${{ steps.find-files.outputs.files }} --generate-baseline=baseline.json
          git checkout -m $CURRENT
          cat baseline.json

      - name: Verify examples
        if: ${{ steps.find-files.outputs.files }}
        run: |
          ../_checker/code-block-checker.php verify:docs `pwd` ${{ steps.find-files.outputs.files }} --baseline=baseline.json --output-format=github
